import type {
  ContractArgumentSpec,
  ContractEnumCaseSpec,
  ContractFunctionSpec,
  ContractPrimitiveTypeName,
  ContractStructFieldSpec,
  ContractTypeRef,
  ContractUnionCaseSpec,
  ContractUserTypeSpec,
  ExtractContractSpecOptions,
  ExtractedContractSpec,
  GenerateContractTypesOptions,
  Network,
} from './types';

const RPC_URLS: Record<Network, string> = {
  mainnet: 'https://soroban-rpc.stellar.org',
  testnet: 'https://soroban-testnet.stellar.org',
};

const specCache = new Map<string, CachedContractSpec>();
const inFlightSpecs = new Map<string, Promise<CachedContractSpec>>();

interface CachedContractSpec {
  contractId: string;
  network: Network;
  rpcUrl: string;
  wasmHash: `0x${string}`;
  functions: ContractFunctionSpec[];
  types: ContractUserTypeSpec[];
}

/**
 * Extracts and normalizes the on-chain Soroban spec for a deployed contract.
 *
 * Reads the live contract instance from Soroban RPC to obtain the current Wasm
 * hash, then loads the contract Wasm, parses the embedded `contractspecv0`
 * section, and returns a JSON-friendly representation of the functions and
 * user-defined types.
 */
export async function extractContractSpec(
  contractId: string,
  network?: Network,
): Promise<ExtractedContractSpec>;
export async function extractContractSpec(
  contractId: string,
  options: ExtractContractSpecOptions,
): Promise<ExtractedContractSpec>;
export async function extractContractSpec(
  contractId: string,
  networkOrOptions: Network | ExtractContractSpecOptions = 'testnet',
): Promise<ExtractedContractSpec> {
  const options = normalizeOptions(networkOrOptions);
  const wasmHash = await fetchContractWasmHash(contractId, options.rpcUrl);
  const cacheKey = `${options.network}:${options.rpcUrl}:${contractId}:${wasmHash}`;

  let cached = options.bypassCache ? undefined : specCache.get(cacheKey);
  if (!cached) {
    const pending = options.bypassCache ? undefined : inFlightSpecs.get(cacheKey);
    if (pending) {
      cached = await pending;
    } else {
      const work = loadAndNormalizeContractSpec(
        contractId,
        options.network,
        options.rpcUrl,
        wasmHash,
      );
      if (!options.bypassCache) {
        inFlightSpecs.set(cacheKey, work);
      }
      try {
        cached = await work;
        if (!options.bypassCache) {
          specCache.set(cacheKey, cached);
        }
      } finally {
        if (!options.bypassCache) {
          inFlightSpecs.delete(cacheKey);
        }
      }
    }
  }

  if (options.generateTypes) {
    return {
      ...cached,
      typescript: generateContractTypes(
        cached,
        options.generateTypes === true ? undefined : options.generateTypes,
      ),
    };
  }

  return cached;
}

/**
 * Generates deterministic TypeScript declarations from a normalized Stellar
 * contract spec.
 */
export function generateContractTypes(
  spec: Pick<ExtractedContractSpec, 'contractId' | 'functions' | 'types'>,
  options: GenerateContractTypesOptions = {},
): string {
  const lines: string[] = [];
  const contractName = sanitizeTypeName(options.contractName ?? 'SorobanContract');
  const argsName = (fnName: string) => `${toPascalCase(fnName)}Args`;
  const resultName = (fnName: string) => `${toPascalCase(fnName)}Result`;

  lines.push('// Generated by @wraith-protocol/sdk/chains/stellar');
  lines.push(`// Contract: ${spec.contractId}`);
  lines.push('');
  lines.push('export type ContractResult<Ok, Err> = { ok: Ok } | { error: Err };');
  lines.push('');

  for (const typeSpec of spec.types) {
    if (typeSpec.doc) {
      lines.push(renderDocComment(typeSpec.doc));
    }

    switch (typeSpec.kind) {
      case 'struct':
        lines.push(`export interface ${sanitizeTypeName(typeSpec.name)} {`);
        for (const field of typeSpec.fields) {
          if (field.doc) {
            lines.push(indent(renderDocComment(field.doc), 1));
          }
          lines.push(`  ${renderPropertyName(field.name)}: ${renderTypeScriptType(field.type)};`);
        }
        lines.push('}');
        break;
      case 'union': {
        lines.push(`export type ${sanitizeTypeName(typeSpec.name)} =`);
        for (const unionCase of typeSpec.cases) {
          if (unionCase.kind === 'void') {
            lines.push(`  | { tag: '${unionCase.name}' };`);
            continue;
          }
          const values = renderTupleLiteral(unionCase.valueTypes);
          lines.push(`  | { tag: '${unionCase.name}'; values: ${values} };`);
        }
        break;
      }
      case 'enum':
      case 'errorEnum':
        lines.push(`export enum ${sanitizeTypeName(typeSpec.name)} {`);
        for (const enumCase of typeSpec.cases) {
          lines.push(`  ${sanitizeEnumMember(enumCase.name)} = ${enumCase.value},`);
        }
        lines.push('}');
        break;
    }

    lines.push('');
  }

  for (const fn of spec.functions) {
    if (fn.doc) {
      lines.push(renderDocComment(fn.doc));
    }
    lines.push(`export interface ${argsName(fn.name)} {`);
    for (const input of fn.inputs) {
      if (input.doc) {
        lines.push(indent(renderDocComment(input.doc), 1));
      }
      lines.push(`  ${renderPropertyName(input.name)}: ${renderTypeScriptType(input.type)};`);
    }
    lines.push('}');
    lines.push(`export type ${resultName(fn.name)} = ${renderFunctionResultType(fn.outputs)};`);
    lines.push('');
  }

  lines.push(`export interface ${contractName} {`);
  for (const fn of spec.functions) {
    lines.push(
      `  ${renderPropertyName(fn.name)}(args: ${argsName(fn.name)}): ${resultName(fn.name)};`,
    );
  }
  lines.push('}');

  return lines.join('\n').trim();
}

function normalizeOptions(networkOrOptions: Network | ExtractContractSpecOptions): Required<
  Pick<ExtractContractSpecOptions, 'network' | 'rpcUrl' | 'bypassCache'>
> & {
  generateTypes?: boolean | GenerateContractTypesOptions;
} {
  if (typeof networkOrOptions === 'string') {
    return {
      network: networkOrOptions,
      rpcUrl: RPC_URLS[networkOrOptions],
      bypassCache: false,
      generateTypes: undefined,
    };
  }

  const network = networkOrOptions.network ?? 'testnet';
  return {
    network,
    rpcUrl: networkOrOptions.rpcUrl ?? RPC_URLS[network],
    bypassCache: networkOrOptions.bypassCache ?? false,
    generateTypes: networkOrOptions.generateTypes,
  };
}

async function fetchContractWasmHash(contractId: string, rpcUrl: string): Promise<`0x${string}`> {
  const stellar = await import('@stellar/stellar-sdk');
  const server = new stellar.rpc.Server(rpcUrl);
  const contractKey = new stellar.Contract(contractId).getFootprint();
  const response = await server.getLedgerEntries(contractKey);
  const contractData = response.entries[0]?.val?.contractData();

  if (!contractData) {
    throw new Error(`Contract instance not found for ${contractId}`);
  }

  const wasmHash = contractData.val().instance().executable().wasmHash();
  return bytesToHex(wasmHash);
}

async function loadAndNormalizeContractSpec(
  contractId: string,
  network: Network,
  rpcUrl: string,
  wasmHash: `0x${string}`,
): Promise<CachedContractSpec> {
  const stellar = await import('@stellar/stellar-sdk');
  const server = new stellar.rpc.Server(rpcUrl);
  const wasm = await server.getContractWasmByHash(wasmHash.slice(2), 'hex');
  const entries = await readSpecEntriesFromWasm(stellar, wasm);

  // Constructing Contract.Spec validates the entry stream against Stellar's
  // own contract-spec parser before we normalize it into SDK-owned types.
  new stellar.contract.Spec(entries);

  const normalized = normalizeEntries(entries);
  return {
    contractId,
    network,
    rpcUrl,
    wasmHash,
    ...normalized,
  };
}

async function readSpecEntriesFromWasm(
  stellar: typeof import('@stellar/stellar-sdk'),
  wasm: Buffer,
): Promise<import('@stellar/stellar-sdk').xdr.ScSpecEntry[]> {
  const sections = await readSpecSections(wasm);
  if (!sections.length) {
    throw new Error('Could not obtain contract spec from wasm');
  }

  const sectionBytes = Buffer.from(sections[0]);
  const reader = new stellar.cereal.XdrReader(sectionBytes);
  const entries: import('@stellar/stellar-sdk').xdr.ScSpecEntry[] = [];

  while (!reader.eof) {
    entries.push(stellar.xdr.ScSpecEntry.read(reader as unknown as Buffer));
  }

  return entries;
}

async function readSpecSections(wasm: Buffer): Promise<Uint8Array[]> {
  try {
    const wasmArrayBuffer = wasm.buffer.slice(
      wasm.byteOffset,
      wasm.byteOffset + wasm.byteLength,
    ) as ArrayBuffer;
    const module = await WebAssembly.compile(wasmArrayBuffer);
    return WebAssembly.Module.customSections(module, 'contractspecv0').map(
      (section) => new Uint8Array(section),
    );
  } catch {
    return parseWasmCustomSections(wasm).get('contractspecv0') ?? [];
  }
}

function parseWasmCustomSections(buffer: Buffer): Map<string, Uint8Array[]> {
  const sections = new Map<string, Uint8Array[]>();
  const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  let offset = 0;

  const read = (length: number): Uint8Array => {
    if (offset + length > buffer.byteLength) {
      throw new Error('Buffer overflow while parsing wasm');
    }
    const bytes = new Uint8Array(arrayBuffer, offset, length);
    offset += length;
    return bytes;
  };

  if ([...read(4)].join() !== '0,97,115,109') {
    throw new Error('Invalid WASM magic');
  }
  if ([...read(4)].join() !== '1,0,0,0') {
    throw new Error('Invalid WASM version');
  }

  while (offset < buffer.byteLength) {
    const sectionId = read(1)[0];
    const sectionLength = readVarUint32(read);
    const sectionStart = offset;

    if (sectionId !== 0) {
      offset += sectionLength;
      continue;
    }

    const nameLength = readVarUint32(read);
    if (nameLength === 0 || offset + nameLength > sectionStart + sectionLength) {
      offset = sectionStart + sectionLength;
      continue;
    }

    const nameBytes = read(nameLength);
    const payload = read(sectionLength - (offset - sectionStart));

    try {
      const name = new TextDecoder('utf-8', { fatal: true }).decode(nameBytes);
      if (payload.length > 0) {
        const existing = sections.get(name) ?? [];
        existing.push(payload);
        sections.set(name, existing);
      }
    } catch {
      // Ignore malformed custom section names.
    }
  }

  return sections;
}

function readVarUint32(read: (length: number) => Uint8Array): number {
  let value = 0;
  let shift = 0;

  while (true) {
    const byte = read(1)[0];
    value |= (byte & 0x7f) << shift;
    if ((byte & 0x80) === 0) {
      return value >>> 0;
    }
    shift += 7;
    if (shift >= 32) {
      throw new Error('Invalid WASM varuint32 value');
    }
  }
}

function normalizeEntries(
  entries: import('@stellar/stellar-sdk').xdr.ScSpecEntry[],
): Pick<CachedContractSpec, 'functions' | 'types'> {
  const functions: ContractFunctionSpec[] = [];
  const types: ContractUserTypeSpec[] = [];

  for (const entry of entries) {
    switch (entry.switch().name) {
      case 'scSpecEntryFunctionV0':
        functions.push(normalizeFunction(entry.functionV0()));
        break;
      case 'scSpecEntryUdtStructV0':
        types.push(normalizeStruct(entry.udtStructV0()));
        break;
      case 'scSpecEntryUdtUnionV0':
        types.push(normalizeUnion(entry.udtUnionV0()));
        break;
      case 'scSpecEntryUdtEnumV0':
        types.push(normalizeEnum(entry.udtEnumV0()));
        break;
      case 'scSpecEntryUdtErrorEnumV0':
        types.push(normalizeErrorEnum(entry.udtErrorEnumV0()));
        break;
      default:
        break;
    }
  }

  return { functions, types };
}

function normalizeFunction(
  fn: import('@stellar/stellar-sdk').xdr.ScSpecFunctionV0,
): ContractFunctionSpec {
  return {
    name: asString(fn.name()),
    doc: normalizeDoc(fn.doc()),
    inputs: fn.inputs().map((input) => normalizeArgument(input)),
    outputs: fn.outputs().map((output) => normalizeType(output)),
  };
}

function normalizeArgument(
  input: import('@stellar/stellar-sdk').xdr.ScSpecFunctionInputV0,
): ContractArgumentSpec {
  return {
    name: asString(input.name()),
    doc: normalizeDoc(input.doc()),
    type: normalizeType(input.type()),
  };
}

function normalizeStruct(
  struct: import('@stellar/stellar-sdk').xdr.ScSpecUdtStructV0,
): Extract<ContractUserTypeSpec, { kind: 'struct' }> {
  return {
    kind: 'struct',
    name: asString(struct.name()),
    doc: normalizeDoc(struct.doc()),
    library: normalizeDoc(struct.lib()),
    fields: struct.fields().map((field) => normalizeStructField(field)),
  };
}

function normalizeStructField(
  field: import('@stellar/stellar-sdk').xdr.ScSpecUdtStructFieldV0,
): ContractStructFieldSpec {
  return {
    name: asString(field.name()),
    doc: normalizeDoc(field.doc()),
    type: normalizeType(field.type()),
  };
}

function normalizeUnion(
  union: import('@stellar/stellar-sdk').xdr.ScSpecUdtUnionV0,
): Extract<ContractUserTypeSpec, { kind: 'union' }> {
  return {
    kind: 'union',
    name: asString(union.name()),
    doc: normalizeDoc(union.doc()),
    library: normalizeDoc(union.lib()),
    cases: union.cases().map((unionCase) => normalizeUnionCase(unionCase)),
  };
}

function normalizeUnionCase(
  unionCase: import('@stellar/stellar-sdk').xdr.ScSpecUdtUnionCaseV0,
): ContractUnionCaseSpec {
  switch (unionCase.switch().name) {
    case 'scSpecUdtUnionCaseVoidV0': {
      const voidCase = unionCase.voidCase();
      return {
        kind: 'void',
        name: asString(voidCase.name()),
        doc: normalizeDoc(voidCase.doc()),
      };
    }
    case 'scSpecUdtUnionCaseTupleV0': {
      const tupleCase = unionCase.tupleCase();
      return {
        kind: 'tuple',
        name: asString(tupleCase.name()),
        doc: normalizeDoc(tupleCase.doc()),
        valueTypes: tupleCase.type().map((valueType) => normalizeType(valueType)),
      };
    }
    default:
      throw new Error(`Unsupported Soroban union case: ${unionCase.switch().name}`);
  }
}

function normalizeEnum(
  enumType: import('@stellar/stellar-sdk').xdr.ScSpecUdtEnumV0,
): Extract<ContractUserTypeSpec, { kind: 'enum' }> {
  return {
    kind: 'enum',
    name: asString(enumType.name()),
    doc: normalizeDoc(enumType.doc()),
    library: normalizeDoc(enumType.lib()),
    cases: enumType.cases().map((enumCase) => normalizeEnumCase(enumCase)),
  };
}

function normalizeErrorEnum(
  enumType: import('@stellar/stellar-sdk').xdr.ScSpecUdtErrorEnumV0,
): Extract<ContractUserTypeSpec, { kind: 'errorEnum' }> {
  return {
    kind: 'errorEnum',
    name: asString(enumType.name()),
    doc: normalizeDoc(enumType.doc()),
    library: normalizeDoc(enumType.lib()),
    cases: enumType.cases().map((enumCase) => normalizeEnumCase(enumCase)),
  };
}

function normalizeEnumCase(
  enumCase:
    | import('@stellar/stellar-sdk').xdr.ScSpecUdtEnumCaseV0
    | import('@stellar/stellar-sdk').xdr.ScSpecUdtErrorEnumCaseV0,
): ContractEnumCaseSpec {
  return {
    name: asString(enumCase.name()),
    doc: normalizeDoc(enumCase.doc()),
    value: enumCase.value(),
  };
}

function normalizeType(typeDef: import('@stellar/stellar-sdk').xdr.ScSpecTypeDef): ContractTypeRef {
  switch (typeDef.switch().name) {
    case 'scSpecTypeVal':
      return primitiveType('val');
    case 'scSpecTypeBool':
      return primitiveType('bool');
    case 'scSpecTypeVoid':
      return primitiveType('void');
    case 'scSpecTypeError':
      return primitiveType('error');
    case 'scSpecTypeU32':
      return primitiveType('u32');
    case 'scSpecTypeI32':
      return primitiveType('i32');
    case 'scSpecTypeU64':
      return primitiveType('u64');
    case 'scSpecTypeI64':
      return primitiveType('i64');
    case 'scSpecTypeTimepoint':
      return primitiveType('timepoint');
    case 'scSpecTypeDuration':
      return primitiveType('duration');
    case 'scSpecTypeU128':
      return primitiveType('u128');
    case 'scSpecTypeI128':
      return primitiveType('i128');
    case 'scSpecTypeU256':
      return primitiveType('u256');
    case 'scSpecTypeI256':
      return primitiveType('i256');
    case 'scSpecTypeBytes':
      return primitiveType('bytes');
    case 'scSpecTypeString':
      return primitiveType('string');
    case 'scSpecTypeSymbol':
      return primitiveType('symbol');
    case 'scSpecTypeAddress':
      return primitiveType('address');
    case 'scSpecTypeOption':
      return {
        kind: 'option',
        valueType: normalizeType(typeDef.option().valueType()),
      };
    case 'scSpecTypeResult': {
      const result = typeDef.result();
      return {
        kind: 'result',
        okType: normalizeType(result.okType()),
        errorType: normalizeType(result.errorType()),
      };
    }
    case 'scSpecTypeVec':
      return {
        kind: 'vec',
        elementType: normalizeType(typeDef.vec().elementType()),
      };
    case 'scSpecTypeMap': {
      const map = typeDef.map();
      return {
        kind: 'map',
        keyType: normalizeType(map.keyType()),
        valueType: normalizeType(map.valueType()),
      };
    }
    case 'scSpecTypeTuple':
      return {
        kind: 'tuple',
        valueTypes: typeDef
          .tuple()
          .valueTypes()
          .map((valueType) => normalizeType(valueType)),
      };
    case 'scSpecTypeBytesN':
      return {
        kind: 'bytesN',
        n: typeDef.bytesN().n(),
      };
    case 'scSpecTypeUdt':
      return {
        kind: 'udt',
        name: asString(typeDef.udt().name()),
      };
    default:
      throw new Error(`Unsupported Soroban type: ${typeDef.switch().name}`);
  }
}

function primitiveType(name: ContractPrimitiveTypeName): ContractTypeRef {
  return { kind: 'primitive', name };
}

function renderFunctionResultType(outputs: ContractTypeRef[]): string {
  if (outputs.length === 0) {
    return 'void';
  }
  if (outputs.length === 1) {
    return renderTypeScriptType(outputs[0]);
  }
  return renderTupleLiteral(outputs);
}

function renderTupleLiteral(types: ContractTypeRef[]): string {
  return `[${types.map((type) => renderTypeScriptType(type)).join(', ')}]`;
}

function renderTypeScriptType(type: ContractTypeRef): string {
  switch (type.kind) {
    case 'primitive':
      return renderPrimitiveType(type.name);
    case 'option':
      return `${renderTypeScriptType(type.valueType)} | undefined`;
    case 'result':
      return `ContractResult<${renderTypeScriptType(type.okType)}, ${renderTypeScriptType(type.errorType)}>`;
    case 'vec':
      return `Array<${renderTypeScriptType(type.elementType)}>`;
    case 'map':
      return `Array<[${renderTypeScriptType(type.keyType)}, ${renderTypeScriptType(type.valueType)}]>`;
    case 'tuple':
      return renderTupleLiteral(type.valueTypes);
    case 'bytesN':
      return 'Uint8Array';
    case 'udt':
      return sanitizeTypeName(type.name);
  }
}

function renderPrimitiveType(name: ContractPrimitiveTypeName): string {
  switch (name) {
    case 'val':
      return 'unknown';
    case 'bool':
      return 'boolean';
    case 'void':
      return 'void';
    case 'error':
      return 'Error';
    case 'u32':
    case 'i32':
      return 'number';
    case 'u64':
    case 'i64':
    case 'timepoint':
    case 'duration':
    case 'u128':
    case 'i128':
    case 'u256':
    case 'i256':
      return 'bigint';
    case 'bytes':
      return 'Uint8Array';
    case 'string':
    case 'symbol':
    case 'address':
      return 'string';
  }
}

function renderPropertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function sanitizeTypeName(name: string): string {
  const pascal = toPascalCase(name);
  return /^[A-Za-z_$]/.test(pascal) ? pascal : `T${pascal}`;
}

function sanitizeEnumMember(name: string): string {
  const member = toPascalCase(name);
  return /^[A-Za-z_$]/.test(member) ? member : `E${member}`;
}

function toPascalCase(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9]+/g, ' ');
  const parts = cleaned.split(' ').filter(Boolean);
  if (parts.length === 0) {
    return 'GeneratedType';
  }
  return parts.map((part) => part[0]!.toUpperCase() + part.slice(1)).join('');
}

function renderDocComment(doc: string): string {
  const lines = doc.split(/\r?\n/);
  if (lines.length === 1) {
    return `/** ${lines[0]} */`;
  }
  return ['/**', ...lines.map((line) => ` * ${line}`), ' */'].join('\n');
}

function indent(value: string, level: number): string {
  const prefix = '  '.repeat(level);
  return value
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}

function asString(value: string | Buffer | Uint8Array): string {
  if (typeof value === 'string') {
    return value;
  }
  return Buffer.from(value).toString('utf8');
}

function normalizeDoc(value: string | Buffer | Uint8Array): string | undefined {
  const doc = asString(value).trim();
  return doc.length > 0 ? doc : undefined;
}

function bytesToHex(bytes: Uint8Array): `0x${string}` {
  return `0x${Buffer.from(bytes).toString('hex')}`;
}
